- name: ping sample
  hosts: dummyservers
  tasks:
    - name: live check
      net_ping:
        dest: 172.16.168.107
        count: 5
    - name: internet check
      net_ping:
        dest: google.com
        count: 5
      

