- name: ping sample
  hosts: all
  tasks:
    - name: live check
      shell: ping 172.16.168.107 -c 3
      register: p
      
    - name: internet check
      shell: ping google.com -c 3
      register: q
      
    - debug: var=p.stdout_lines
    - debug: var=q.stdout_lines
